//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinhasVendas.ABC_Translate {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MinhasVendas.ABC_Translate.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add customer.
        /// </summary>
        internal static string Add_customer {
            get {
                return ResourceManager.GetString("Add customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add Product.
        /// </summary>
        internal static string Add_Product {
            get {
                return ResourceManager.GetString("Add Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add this customer to the sale?.
        /// </summary>
        internal static string Add_this_customer_to_the_sale {
            get {
                return ResourceManager.GetString("Add this customer to the sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Add this product to the sale?.
        /// </summary>
        internal static string Add_this_product_to_the_sale {
            get {
                return ResourceManager.GetString("Add this product to the sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All empty.
        /// </summary>
        internal static string All_empty {
            get {
                return ResourceManager.GetString("All empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anonymous.
        /// </summary>
        internal static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aquatic theme.
        /// </summary>
        internal static string Aquatic_theme {
            get {
                return ResourceManager.GetString("Aquatic theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Choose theme.
        /// </summary>
        internal static string Choose_theme {
            get {
                return ResourceManager.GetString("Choose theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Client.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customer.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Customers.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dark theme.
        /// </summary>
        internal static string Dark_theme {
            get {
                return ResourceManager.GetString("Dark theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Default theme.
        /// </summary>
        internal static string Default_theme {
            get {
                return ResourceManager.GetString("Default theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Description of my company.
        /// </summary>
        internal static string Description_of_my_company {
            get {
                return ResourceManager.GetString("Description of my company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details of Customer.
        /// </summary>
        internal static string Details_of_Customer {
            get {
                return ResourceManager.GetString("Details of Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Details of Product.
        /// </summary>
        internal static string Details_of_Product {
            get {
                return ResourceManager.GetString("Details of Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you really want to delete this customer?.
        /// </summary>
        internal static string Do_you_really_want_to_delete_this_customer {
            get {
                return ResourceManager.GetString("Do you really want to delete this customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Do you really want to delete this sale?.
        /// </summary>
        internal static string Do_you_really_want_to_delete_this_sale {
            get {
                return ResourceManager.GetString("Do you really want to delete this sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Earnings.
        /// </summary>
        internal static string Earnings {
            get {
                return ResourceManager.GetString("Earnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Customer.
        /// </summary>
        internal static string Edit_Customer {
            get {
                return ResourceManager.GetString("Edit Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Product.
        /// </summary>
        internal static string Edit_Product {
            get {
                return ResourceManager.GetString("Edit Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit Theme.
        /// </summary>
        internal static string Edit_Theme {
            get {
                return ResourceManager.GetString("Edit Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Edit User.
        /// </summary>
        internal static string Edit_User {
            get {
                return ResourceManager.GetString("Edit User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the customers name.
        /// </summary>
        internal static string Enter_the_customers_name {
            get {
                return ResourceManager.GetString("Enter the customers name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the product name.
        /// </summary>
        internal static string Enter_the_product_name {
            get {
                return ResourceManager.GetString("Enter the product name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the quantity of product.
        /// </summary>
        internal static string Enter_the_quantity_of_product {
            get {
                return ResourceManager.GetString("Enter the quantity of product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enter the value.
        /// </summary>
        internal static string Enter_the_value {
            get {
                return ResourceManager.GetString("Enter the value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclude.
        /// </summary>
        internal static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fire theme.
        /// </summary>
        internal static string Fire_theme {
            get {
                return ResourceManager.GetString("Fire theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lemon theme.
        /// </summary>
        internal static string Lemon_theme {
            get {
                return ResourceManager.GetString("Lemon theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a My customers.
        /// </summary>
        internal static string My_customers {
            get {
                return ResourceManager.GetString("My customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name, Product and Unit empty.
        /// </summary>
        internal static string Name__Product_and_Unit_empty {
            get {
                return ResourceManager.GetString("Name, Product and Unit empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name, Products and Value empty.
        /// </summary>
        internal static string Name__Products_and_Value_empty {
            get {
                return ResourceManager.GetString("Name, Products and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name, Unit and Value empty.
        /// </summary>
        internal static string Name__Unit_and_Value_empty {
            get {
                return ResourceManager.GetString("Name, Unit and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name and Product empty.
        /// </summary>
        internal static string Name_and_Product_empty {
            get {
                return ResourceManager.GetString("Name and Product empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name and Unit empty.
        /// </summary>
        internal static string Name_and_Unit_empty {
            get {
                return ResourceManager.GetString("Name and Unit empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name and Value empty.
        /// </summary>
        internal static string Name_and_Value_empty {
            get {
                return ResourceManager.GetString("Name and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name empty.
        /// </summary>
        internal static string Name_empty {
            get {
                return ResourceManager.GetString("Name empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Name of my company.
        /// </summary>
        internal static string Name_of_my_company {
            get {
                return ResourceManager.GetString("Name of my company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Customer.
        /// </summary>
        internal static string New_Customer {
            get {
                return ResourceManager.GetString("New Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Product.
        /// </summary>
        internal static string New_Product {
            get {
                return ResourceManager.GetString("New Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New Sale.
        /// </summary>
        internal static string New_Sale {
            get {
                return ResourceManager.GetString("New Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notes.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you have added something at the entrance of the units!.
        /// </summary>
        internal static string Please_check_if_you_have_added_something_at_the_entrance_of_the_units {
            get {
                return ResourceManager.GetString("Please check if you have added something at the entrance of the units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you have added something at the entrance of the units, and the value!.
        /// </summary>
        internal static string Please_check_if_you_have_added_something_at_the_entrance_of_the_units__and_the_value {
            get {
                return ResourceManager.GetString("Please check if you have added something at the entrance of the units, and the va" +
                        "lue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you have added something at the entry of the name or product, and the units!.
        /// </summary>
        internal static string Please_check_if_you_have_added_something_at_the_entry_of_the_name_or_product__and_the_units {
            get {
                return ResourceManager.GetString("Please check if you have added something at the entry of the name or product, and" +
                        " the units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you have added something in the name or product entry, and the value!.
        /// </summary>
        internal static string Please_check_if_you_have_added_something_in_the_name_or_product_entry__and_the_value {
            get {
                return ResourceManager.GetString("Please check if you have added something in the name or product entry, and the va" +
                        "lue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please check if you have added something in the value entry!.
        /// </summary>
        internal static string Please_check_if_you_have_added_something_in_the_value_entry {
            get {
                return ResourceManager.GetString("Please check if you have added something in the value entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure that you have added something in the Name and Units!.
        /// </summary>
        internal static string Please_make_sure_that_you_have_added_something_in_the_Name_and_Units {
            get {
                return ResourceManager.GetString("Please make sure that you have added something in the Name and Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something at the product entry, Units and Value!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_at_the_product_entry__Units_and_Value {
            get {
                return ResourceManager.GetString("Please make sure you have added something at the product entry, Units and Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in all entries!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_all_entries {
            get {
                return ResourceManager.GetString("Please make sure you have added something in all entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Name, Product and Units entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Name__Product_and_Units_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Name, Product and Units entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Name, Product and Value entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Name__Product_and_Value_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Name, Product and Value entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Name and Product entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Name_and_Product_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Name and Product entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Name and Value entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Name_and_Value_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Name and Value entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Name entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Name_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Name entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you have added something in the Product entry!.
        /// </summary>
        internal static string Please_make_sure_you_have_added_something_in_the_Product_entry {
            get {
                return ResourceManager.GetString("Please make sure you have added something in the Product entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please make sure you&apos;ve added something in the Name, Units, and Value entry!.
        /// </summary>
        internal static string Please_make_sure_you_ve_added_something_in_the_Name__Units__and_Value_entry {
            get {
                return ResourceManager.GetString("Please make sure you\'ve added something in the Name, Units, and Value entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product, Unit and Value empty.
        /// </summary>
        internal static string Product__Unit_and_Value_empty {
            get {
                return ResourceManager.GetString("Product, Unit and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product and Unit empty.
        /// </summary>
        internal static string Product_and_Unit_empty {
            get {
                return ResourceManager.GetString("Product and Unit empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product and Value empty.
        /// </summary>
        internal static string Product_and_Value_empty {
            get {
                return ResourceManager.GetString("Product and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Product empty.
        /// </summary>
        internal static string Product_empty {
            get {
                return ResourceManager.GetString("Product empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Products.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale.
        /// </summary>
        internal static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale added Successfully!.
        /// </summary>
        internal static string Sale_added_Successfully {
            get {
                return ResourceManager.GetString("Sale added Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale completed.
        /// </summary>
        internal static string Sale_completed {
            get {
                return ResourceManager.GetString("Sale completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale Conclude.
        /// </summary>
        internal static string Sale_Conclude {
            get {
                return ResourceManager.GetString("Sale Conclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale Edit.
        /// </summary>
        internal static string Sale_Edit {
            get {
                return ResourceManager.GetString("Sale Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sale Information.
        /// </summary>
        internal static string Sale_Information {
            get {
                return ResourceManager.GetString("Sale Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shopped.
        /// </summary>
        internal static string Shopped {
            get {
                return ResourceManager.GetString("Shopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stock of products.
        /// </summary>
        internal static string Stock_of_products {
            get {
                return ResourceManager.GetString("Stock of products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Successfully added!.
        /// </summary>
        internal static string Successfully_added {
            get {
                return ResourceManager.GetString("Successfully added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total Value.
        /// </summary>
        internal static string Total_Value {
            get {
                return ResourceManager.GetString("Total Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unit and Value empty.
        /// </summary>
        internal static string Unit_and_Value_empty {
            get {
                return ResourceManager.GetString("Unit and Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unit empty.
        /// </summary>
        internal static string Unit_empty {
            get {
                return ResourceManager.GetString("Unit empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Units.
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value empty.
        /// </summary>
        internal static string Value_empty {
            get {
                return ResourceManager.GetString("Value empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value Product.
        /// </summary>
        internal static string Value_Product {
            get {
                return ResourceManager.GetString("Value Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a View your sales.
        /// </summary>
        internal static string View_your_Sales {
            get {
                return ResourceManager.GetString("View your Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
